Feature 271 swap orders
bitzlato/peatio pull request #276
Opened 2021-11-22 15:53 UTC by Nitr

2021-11-23 08:23 UTC, radanisk commented on app/models/swap_order.rb
> +  # rubocop:disable Rails/RedundantForeignKey
рубокоп не прав? ) `foreign_key: :market_id` разве не лишнее? )

2021-11-23 08:25 UTC, radanisk commented on app/models/swap_order.rb
> +  # rubocop:disable Rails/InverseOf
вроде как можно указать `inverse_of: false` в этом случае, и все будут довольны :) https://docs.rubocop.org/rubocop-rails/cops_rails.html#examples-47

2021-11-23 08:29 UTC, radanisk commented on db/migrate/20211122110601_create_swap_orders.rb
> +      t.integer :side, default: 0
`null: false` ?

2021-11-23 08:35 UTC, radanisk commented on app/services/order_services/create_swap_order.rb
> +      create_order_result = CreateOrder.new(member: @member).perform(params.merge(ord_type: 'limit'))
В общую транзакцию может положить создание SwapOrder и CreateOrder?

2021-11-23 15:03 UTC, dapi commented on app/workers/daemons/swap_order_status_checker.rb
> +        end
У SwapOrder НЕ такие состояния как у Order

2021-11-23 15:06 UTC, dapi commented on app/api/v2/order_helpers.rb
> +      def create_order(attrs, order_create_service: :order)
Делай новый метод, не надо этот менять

2021-11-30 09:48 UTC, radanisk requested changes

2021-11-30 09:48 UTC, radanisk commented on app/api/v2/entities/swap_order.rb
> +            desc: "One of 'wait', 'done', or 'cancel'."\
Будет ли здесь pending?

2021-11-30 09:48 UTC, radanisk commented on app/api/v2/entities/swap_order.rb
> +            desc: "One of 'wait', 'done', or 'cancel'."\
Может через values перечислить возможные значения поля?

2021-11-30 09:48 UTC, radanisk commented on app/api/v2/market/named_params.rb
> +                   desc: -> { V2::Entities::SwapOrder.documentation[:price] }
```suggestion
                   desc: -> { API::V2::Entities::SwapOrder.documentation[:price][:desc] }
```

2021-11-30 09:48 UTC, radanisk commented on app/api/v2/market/swap_orders.rb
> +                     desc: -> { V2::Entities::SwapOrder.documentation[:id] }
```suggestion
                     desc: -> { API::V2::Entities::SwapOrder.documentation[:id][:desc] }
```

2021-11-30 09:48 UTC, radanisk commented on app/api/v2/order_helpers.rb
> +          if DESCRIBED_ERRORS_MESSAGES.include?(error_message.to_s)
У OrderServices::CreateSwapOrder свои ошибки, наскольк вижу. Что-то из DESCRIBED_ERRORS_MESSAGES разве вернётся?

2021-11-30 09:58 UTC, radanisk commented on app/models/swap_order.rb
> +  belongs_to :member, optional: false, inverse_of: false
Почему inverse_of: false? Есть же релейшен на том конце.

2021-11-30 10:01 UTC, radanisk commented on app/models/swap_order.rb
> +             .with_state(:open, :wait)
open и wait не одно и то же?

2021-11-30 10:01 UTC, radanisk commented on app/models/swap_order.rb
> +             .with_state(:open, :wait)
аналогично комментарию на 30-ой строчке

2021-11-30 10:28 UTC, Nitr commented on app/api/v2/order_helpers.rb
> +          if DESCRIBED_ERRORS_MESSAGES.include?(error_message.to_s)
Да, все ошибки из OrderCreate.
```failure(errors: create_order_result.errors)```

2021-12-03 16:48 UTC, dapi requested changes
Мощно!

2021-12-03 16:48 UTC, dapi commented on app/api/v2/entities/swap_order.rb
> +          :market_id,
У SwapOrder-е нет market_id. SwapOrder это обмен одной валюты на другую. Он может создаваться даже между валютами по которым нет прямого рынка.

Хотя сейчас мы кросс-обмен не поддерживаем, но привязываться к market_id не стоит сразу

2021-12-03 16:48 UTC, dapi commented on app/api/v2/entities/swap_order.rb
> +          :request_price,
Что это за параметр?

2021-12-03 16:48 UTC, dapi commented on app/api/v2/entities/swap_order.rb
> +          :inverse_price,
Что это за параметр?

2021-12-03 16:48 UTC, dapi commented on app/api/v2/entities/swap_price.rb
> +          :inverse_price,
Что-то мне подсказывает что это большая ошибка. Не должно быть в SwapOrder такого параметра. Не бывает инверсионной цены.

Если я за 1 биткойн получаю 100 USD, это не означает что я за 100 USD куплю 1 биткойн.

2021-12-03 16:48 UTC, dapi commented on app/api/v2/entities/swap_price.rb
> +        end
IMHO лучше это сразу делать при экспозировании через value, как во всех презенртерах

2021-12-03 16:48 UTC, dapi commented on app/api/v2/market/named_params.rb
> +          requires :price,
Это цена по которой ему предлагали?

2021-12-03 16:48 UTC, dapi commented on app/api/v2/order_helpers.rb
> +      def create_swap_order(attrs)
А зачем этот метод вытаскивать в Helper если он используется только в одном месте?

2021-12-03 16:48 UTC, dapi commented on app/api/v2/order_helpers.rb
> +          if DESCRIBED_ERRORS_MESSAGES.include?(error_message.to_s)
У SwapOrder совсем другой перечень ошибок.

2021-12-03 16:48 UTC, dapi commented on app/api/v2/public/mount.rb
> +        mount Public::Swap
Swaps, множественное число

2021-12-03 16:48 UTC, dapi commented on app/api/v2/public/swap.rb
> +          swap_price_service = CurrencyServices::SwapPrice.new(from_currency: from_currency, to_currency: to_currency,
```
Rails.cache.fetch([:swap_price, from_currency, to_currency, request_currency], expire...) do
CurrencyServices::SwapPrice.new( ..)
end
```

2021-12-03 16:48 UTC, dapi commented on app/api/v2/public/swap.rb
> +      class Swap < Grape::API
Я бы не делал отдельный ресурс, а сделал это все в swap_orders, потому что это все о том-же

2021-12-03 16:48 UTC, dapi commented on app/services/currency_services/swap_price.rb
> +  class SwapPrice
Это класс свопит цены? Не понятно название. Что за CurrencyServices? Зачем этот namespace?

Назови класс так, чтобы было понятно что он делает.

2021-12-03 16:48 UTC, dapi commented on app/services/currency_services/swap_price.rb
> +  class SwapPrice
И по-моему этот класс делает слишком много.

Есть одно дело - узнать цену рынка. Другое - назвать цену обмена.

Это два разных сервиса.

Один использует другой.

А тут все намешано

2021-12-03 16:48 UTC, dapi commented on app/services/order_services/create_swap_order.rb
> +  class CreateSwapOrder
SwapOrderCreator

2021-12-03 16:49 UTC, dapi commented
Больше всего смущает то что:

1. в swap_orders используется параметр market_id - нужно категорически НЕ привязываться в swap-orderd к market_id. Рынки будут меняться. И будут кросс-свопы.
2. Сервис по вычислению цены перегружен и я не смог понять как он считает цену и удостовериться что он делает это правильно.

2021-12-03 16:51 UTC, dapi commented
Смотри как выглядит модель которая делает почти тоже самое что и SwapOrder - она содержит курс и объёмы для обмена - https://github.com/finfex/larry/blob/master/app/models/rate_calculation.rb
А вот как выглядит сервис для расчета цены - https://github.com/finfex/larry/blob/master/app/services/rate_calculator.rb

2021-12-03 16:53 UTC, dapi requested changes

2021-12-03 16:53 UTC, dapi commented on app/models/swap_order.rb
> +  enumerize :state, in: STATES, scope: true
используй enum, не надо этих извращений с 100,200 и -100, они только путаницу вводят

2021-12-03 18:08 UTC, Nitr commented on app/api/v2/entities/swap_order.rb
> +          :request_price,
его надо переименовать в quote_price

2021-12-03 18:09 UTC, Nitr commented on app/api/v2/entities/swap_order.rb
> +          :market_id,
оставил на всякий случай

2021-12-03 18:20 UTC, Nitr commented on app/api/v2/public/swap.rb
> +          swap_price_service = CurrencyServices::SwapPrice.new(from_currency: from_currency, to_currency: to_currency,
Средняя цена зависит от кол-ва. Например, на рынке есть 0.5btc по цене 100 и 3 по цене 200, ты хочешь 2btc.
(0.5 * 100 + 1.5*200) / 2 = 175;
А так цена будет одинаковая и для amount: 0.5 и для 2, что первое закешируется та и вернется.

2021-12-03 18:26 UTC, Nitr commented on app/api/v2/entities/swap_price.rb
> +          :inverse_price,
Оно используется для вычисления from_volume/to_volume и показывается в форме как в бинансе =)

2021-12-03 18:28 UTC, Nitr commented on app/api/v2/public/swap.rb
> +      class Swap < Grape::API
Лимиты нужно показывать всем пользователям.
А вот создать своп и узнать цену можно в одном месте сделать

2021-12-06 08:18 UTC, Nitr commented on app/api/v2/entities/swap_price.rb
> +        end
+

2021-12-06 08:23 UTC, Nitr commented on app/api/v2/market/named_params.rb
> +          requires :price,
да request_price

2021-12-06 08:25 UTC, Nitr commented on app/api/v2/order_helpers.rb
> +          if DESCRIBED_ERRORS_MESSAGES.include?(error_message.to_s)
часть ошибок из create_order пробрасывается.

2021-12-06 13:12 UTC, merged