stages moving to server with internal ip
bitzlato/peatio pull request #283
Opened 2021-11-29 20:56 UTC by mailer21

2021-11-30 09:24 UTC, radanisk requested changes

2021-11-30 09:24 UTC, radanisk commented on config/deploy/s2.rb
> -      order_cancellator
@mailer21 в s1 не хватает демона order_cancellator, хорошо бы добавить

2021-11-30 09:24 UTC, radanisk commented on config/deploy/s2.rb
> -server '87.98.150.101',
@mailer21 может лучше убрать айпишники серверов с конфигов в переменные окружения?

2021-12-02 07:55 UTC, mailer21 commented on config/deploy/s2.rb
> -      order_cancellator
добавил

2021-12-02 07:55 UTC, mailer21 commented on config/deploy/s2.rb
> -server '87.98.150.101',
убрал

2021-12-02 09:56 UTC, radanisk approved these changes

2021-12-02 09:56 UTC, merged