Issue 286 low hot wallet balance
bitzlato/peatio pull request #291
Opened 2021-12-06 17:13 UTC by Nitr

2021-12-08 11:06 UTC, radanisk commented
@Nitr давай в #market-notifications слать уведомления об этой проблеме

2021-12-08 11:18 UTC, radanisk requested changes

2021-12-08 11:18 UTC, radanisk commented on app/services/withdrawer.rb
> +    rescue Busy, Fail, WalletLowBalance => e
failed - финальный статус для вывода. Может лучше в errored его отправлять, чтоб была возможность повторно его осуществить после решения проблемы?

2021-12-08 11:18 UTC, radanisk commented on app/services/withdrawer.rb
> +      withdraw.blockchain.gateway
Не хотелось бы делать внутри sql-транзакции запрос в стороннюю систему. Плюс баланс кошелька в базе может обновлять с некоторой задержкой. Как вариант, предлагаю чекать баланс кошелька непосредственно в ноде.

2021-12-10 10:16 UTC, radanisk commented on app/models/wallet.rb
> +    amount = withdraw.amount + withdraw.fee
@Nitr тут withdraw.fee точно должен участвовать? 🤔

2021-12-10 10:16 UTC, radanisk commented on app/services/withdrawer.rb
> +      Peatio::SlackNotifier.notifications.ping('There is not enough money in the system wallet to withdraw funds.')
Из уведомления не понятно, с каким именно кошельком проблема произошла...

2021-12-12 06:20 UTC, dapi commented on app/models/wallet.rb
> +    amount = withdraw.amount + withdraw.fee
```
 w = Withdraw.last
 w.amount + w.fee == w.sum
 ```
 
 Думаю правильно тут использовать .sum, а не amount + fee

2021-12-12 06:20 UTC, dapi commented on app/services/withdrawer.rb
> +      @message
Зачем использовать instance?

2021-12-12 06:20 UTC, dapi commented on app/services/withdrawer.rb
> +      @options.merge message: message
А почему тут не instance?

2021-12-12 09:19 UTC, radanisk commented on app/models/wallet.rb
> +    amount = withdraw.amount + withdraw.fee
@dapi при выводе fee вычитается из Wallet'а? в Withdrawer'е вроде как amount используется при создании транзакции... Может и здесь должен только amount участвовать?

2021-12-12 15:31 UTC, Nitr commented on app/services/withdrawer.rb
> +      @message
вызов не существуещего метод message и options.
Либо либо использовать инстанс переменные, либо геттеры сделать `att_reader :message, :options`

2021-12-12 16:00 UTC, Nitr commented on app/models/wallet.rb
> +    amount = withdraw.amount + withdraw.fee
Саша прав. amount выводиться, а fee просто на системно кошельке так и остается лежать.

2021-12-13 07:56 UTC, radanisk approved these changes

2021-12-13 08:29 UTC, merged