Tron gateway
bitzlato/peatio pull request #333
Opened 2022-01-06 16:16 UTC by Nitr

2022-01-10 11:27 UTC, dapi requested changes

2022-01-10 11:27 UTC, dapi commented on app/gateways/ethereum_gateway.rb
> +    @client.extend(Concern)
Я понял ты это делаешь для того чтобы потому из клиента брать утилиты по нормализации.
Заведи лучше для этого отдельный объект - нормализатор и не придется расширять клиента.

2022-01-19 15:11 UTC, radanisk requested changes

2022-01-19 15:11 UTC, radanisk commented on db/structure.sql
> +    rates_limits jsonb DEFAULT '{"minit": 100, "second": 10}'::jsonb NOT NULL,
откуда тут `minit`?

2022-01-19 17:17 UTC, Nitr commented on app/gateways/tron_gateway/address_normalizer.rb
> +      address = reformat_encode_address(address) if address.start_with?('41')
это про как адреса в троне вычисляются
**Use the public key P as the input, by SHA3 get the result H. The length of the public key is 64 bytes, SHA3 uses Keccak256. Use the last 20 bytes of H, and add a byte of 0x41 in front of it, then the address come out.**

2022-01-19 17:22 UTC, Nitr commented on app/gateways/tron_gateway/latest_block_number.rb
> +            .fetch('block')[0]['block_header']['raw_data']['number']
да можно вынести просто в TronGateway

2022-01-19 17:23 UTC, Nitr commented on db/structure.sql
> +    rates_limits jsonb DEFAULT '{"minit": 100, "second": 10}'::jsonb NOT NULL,
а что это такое вообще?

2022-01-19 17:23 UTC, Nitr commented on app/gateways/tron_gateway/current_sync_block.rb
> +    def current_syncing_block
видимо нет, удалю

2022-01-19 17:24 UTC, Nitr commented on app/gateways/tron_gateway.rb
> +    blockchain.currencies.each_with_object({}) { |c, agg| agg[c.contract_address] = c.options['fee_limit'] }
options не хватает в blockchain_currencies.

2022-01-20 09:01 UTC, radanisk commented on app/gateways/tron_gateway.rb
> +    blockchain.currencies.each_with_object({}) { |c, agg| agg[c.contract_address] = c.options['fee_limit'] }
options и не переносился в целом. вместо него отдельные поля contract_address и gas_limit

2022-01-20 09:03 UTC, radanisk commented on app/gateways/tron_gateway/address_normalizer.rb
> +      address = reformat_encode_address(address) if address.start_with?('41')
может его в именованную константу или комментом пояснить?

2022-01-20 10:03 UTC, Nitr commented on app/gateways/tron_gateway.rb
> +    blockchain.currencies.each_with_object({}) { |c, agg| agg[c.contract_address] = c.options['fee_limit'] }
да я это и имел ввиду, надо поле options добавить в blockchain_currencies

2022-01-29 18:51 UTC, dapi commented
Что осталось чтобы влить?

2022-01-30 11:14 UTC, radanisk commented
@dapi ожидает релиза объединения токенов, и, насколько понимаю, могут потребоваться доработки под обновлённую структуру данных

2022-01-30 17:04 UTC, Nitr commented
@dapi @radanisk верно, надо будет пару мест переписать

2022-02-10 16:13 UTC, closed without merging