issue #347. Accept deposits if total skipped amount + account balance…
bitzlato/peatio pull request #348
Opened 2022-01-26 15:43 UTC by Nitr

… amount + new transaction amount bigger ther min_deposit_amount

2022-01-29 10:41 UTC, radanisk requested changes

2022-01-29 10:41 UTC, radanisk commented on app/services/blockchain_service.rb
> +        account_balance = member.legacy_balance_for(currency: currency, kind: :main)
@Nitr это нормально использовать какой-то "legacy"-метод, более актуального нет? :)

2022-01-29 10:41 UTC, radanisk commented on app/services/blockchain_service.rb
> +        if total_amount < currency.min_deposit_amount_money
@Nitr почему в этой формуле участвует account_balance? Это точно корректная формула?

2022-01-29 10:41 UTC, radanisk commented on app/services/blockchain_service.rb
> +        if total_amount < currency.min_deposit_amount_money
@Nitr если всё ж использование аккаунта здесь необходимо, то, думаю, что на него нужен БД-шный лок "FOR UPDATE", иначе на момент его изменения эта проверка может стать неактуальной?

2022-01-29 18:51 UTC, dapi requested changes

2022-01-29 18:51 UTC, dapi commented on app/services/blockchain_service.rb
> +        total_amount = currency.to_money_from_decimal(account_balance) +
Не понял. Причем тут account_balance?

2022-01-29 18:51 UTC, dapi commented on app/services/blockchain_service.rb
> +        account_balance = member.legacy_balance_for(currency: currency, kind: :main)
ТОж мне понял что за Legacy_balance_for и зачем и причем тут вообще баланс. Зачисления или не зачисление депозита Не зависит от баланса вообще никак.

Если пришел депозит надо сложить его сумму и сумму всех скипнитух депозитов и если они больше минимален то зачислить все. если меньше, то новый депозит только пометить как skipd и все

2022-01-31 07:37 UTC, Nitr commented on app/services/blockchain_service.rb
> +        account_balance = member.legacy_balance_for(currency: currency, kind: :main)
Есть два метода: 
`balance_for` - считает через Liability
`legacy_balance_for`- смотрит в поле json поле balance
Мы в основном смотрим через поле balance, я так понимаю?

2022-01-31 08:03 UTC, Nitr commented on app/services/blockchain_service.rb
> +        total_amount = currency.to_money_from_decimal(account_balance) +
убрал

2022-01-31 08:03 UTC, Nitr commented on app/services/blockchain_service.rb
> +        if total_amount < currency.min_deposit_amount_money
убрал

2022-01-31 10:10 UTC, radanisk requested changes

2022-02-08 19:12 UTC, dapi commented on app/services/blockchain_service.rb
> +        skipped_deposits = member.deposits.skipped.lock
вот тут ты добыл просто scope

2022-02-08 19:13 UTC, dapi commented on app/services/blockchain_service.rb
> +        total_skipped_amount = skipped_deposits.sum(&:money_amount) + transaction.amount
тут ты узнал по этому scope сумму

2022-02-10 16:16 UTC, Nitr commented on app/services/blockchain_service.rb
> +        total_skipped_amount = skipped_deposits.sum(&:money_amount) + transaction.amount
тут он запрос c lock for update выполнит. или ты про что?

2022-02-16 07:50 UTC, radanisk approved these changes

2022-02-17 09:55 UTC, dapi commented
Льём?

2022-02-18 11:44 UTC, merged