solana
bitzlato/peatio pull request #386
Opened 2022-02-24 07:19 UTC by unloved

2022-02-24 10:17 UTC, Nitr commented on app/models/blockchain_address.rb
> +      Eth::Key.new priv: private_key_hex
tron

2022-02-24 10:33 UTC, unloved commented on app/models/blockchain_address.rb
> +      Eth::Key.new priv: private_key_hex
я то его не удалял, значит и в мастере нет

2022-02-25 06:31 UTC, dapi commented on Gemfile
> +gem 'solana', path: '/Users/unloved/www/solana'
Мощно

2022-02-25 06:32 UTC, dapi commented on Procfile
> -trade_executor: RAILS_ROOT=. bundle exec ruby ./lib/daemons/amqp_daemon.rb trade_executor
Не понял что тут произошло

2022-02-25 06:32 UTC, dapi commented on app/api/v2/account/withdraws.rb
> +          # error!({ errors: ['account.withdraw.invalid_otp'] }, 422) unless Vault::TOTP.validate?(current_user.uid, params[:otp])
Почему?

2022-02-25 06:36 UTC, dapi requested changes

2022-02-25 06:36 UTC, dapi commented on app/gateways/solana_gateway.rb
> +  attr_reader :blockchain, :api
Зачем api делать публичным методом?

2022-02-25 06:36 UTC, dapi commented on db/migrate/20220222081707_add_fee_payer_to_transactions.rb
> +    add_column :transactions, :fee_payer, :string
Что значит fee_payer? Какие значение оно может принимать?

2022-02-25 06:36 UTC, dapi commented on db/migrate/20220222081707_add_fee_payer_to_transactions.rb
> +    Transaction.update_all("fee_payer = from_address")
Вижу адрес. Тогда лучше переименовать в `fee_payer_address`

2022-02-25 06:36 UTC, dapi commented on db/migrate/20220223194801_add_instruction_id_to_transactions.rb
> +    add_column :transactions, :instruction_id, :integer, default: 0, null: false
Не думаю что дефолтное значение уместно для параметра который используется только в одном блокчейне. Кроме того добавление дефолтного значения приведет к блокировке базы в момент миграции

2022-02-25 06:36 UTC, dapi commented on db/migrate/20220219203454_add_parent_to_payment_address.rb
> +    add_column :payment_addresses, :parent_id, :bigint
Что за parent_id? Это не должно быть reference?

2022-02-25 06:36 UTC, dapi commented on db/migrate/20220219203454_add_parent_to_payment_address.rb
> +  end
@radanisk понимаешь что тут происходит?

2022-02-25 07:39 UTC, unloved commented on Gemfile
> +gem 'solana', path: '/Users/unloved/www/solana'
это поправится в след коммите

2022-02-25 07:39 UTC, unloved commented on Procfile
> -trade_executor: RAILS_ROOT=. bundle exec ruby ./lib/daemons/amqp_daemon.rb trade_executor
это поправится в след коммите

2022-02-25 07:39 UTC, unloved commented on app/api/v2/account/withdraws.rb
> +          # error!({ errors: ['account.withdraw.invalid_otp'] }, 422) unless Vault::TOTP.validate?(current_user.uid, params[:otp])
это поправится в след коммите

2022-02-25 07:42 UTC, unloved commented on db/migrate/20220222081707_add_fee_payer_to_transactions.rb
> +    add_column :transactions, :fee_payer, :string
публичный адрес того кто платить комиссию, он может отличаться от from

2022-02-25 07:52 UTC, unloved commented on db/migrate/20220219203454_add_parent_to_payment_address.rb
> +    add_column :payment_addresses, :parent_id, :bigint
связь между адрес-родителем и его детьми-адресами для токен аккаунтов

2022-02-25 08:14 UTC, radanisk commented on db/migrate/20220219203454_add_parent_to_payment_address.rb
> +  end
@dapi не особо.

2022-02-25 08:17 UTC, radanisk commented on db/migrate/20220222081707_add_fee_payer_to_transactions.rb
> +    add_column :transactions, :fee_payer, :string
А нам точно нужен этот механизм? Мы же и сейчас платим комиссии в рамках других сетей. Можем ли мы здесь придерживаться общего флоу?

2022-02-25 11:05 UTC, Nitr commented on app/models/blockchain_address.rb
> +      Eth::Key.new priv: private_key_hex
так ты его тут переписал и сейчас трон не поддерживается

2022-02-25 11:09 UTC, Nitr commented on app/models/blockchain_address.rb
> +      Eth::Key.new priv: private_key_hex
`Blockchain.lookup_gateway_klass_for(address_type).build_key(private_key_hex)`

2022-03-01 11:27 UTC, radanisk commented on app/gateways/solana_gateway/collector.rb
> +        # raise 'amount must be an Integer' unless amount.is_a? Integer # not money
тут raise нужны или нет?

2022-03-01 11:27 UTC, radanisk commented on app/gateways/solana_gateway/collector.rb
> +      # end
Этот коммент актуальный?

2022-03-01 11:28 UTC, radanisk commented on config/seed/blockchains.yml
> +    gas_factor:      1
зачем подобные изменения? можем их откатить здесь и ниже в файлах?

2022-03-01 11:56 UTC, radanisk commented on lib/tasks/add_solana.rake
> +      wallet.currencies = [sol]
wsol здесь не нужен?

2022-03-01 11:56 UTC, Nitr commented on app/gateways/solana_gateway/block_fetcher.rb
> +      @follow_addresses.nil? || @follow_addresses.intersect?(account_keys.to_set) ||
вроде бы `blockchain.follow_addresses` никогда nil не вернет

2022-03-01 12:13 UTC, Nitr commented on db/migrate/20220227214453_remove_uniquness_of_member_blockchain_index_in_payment_address.rb
> +    add_index :payment_addresses, [:member_id, :blockchain_id]
тут уникальный индекс был нужен чтобы не создавать кучу адресов каждому пользователю в блокчейне.
а сейчас получается можно? или можно как-то так сделать? `add_index :payment_addresses, [:member_id, :blockchain_id, :parent], unique: true`

2022-03-01 12:18 UTC, Nitr commented on app/gateways/solana_gateway/block_fetcher.rb
> +        return nil unless (instruction_data.present? and @follow_addresses.intersect?(instruction[:keys].map{|x| x[:pubkey]}.to_set))
Фильтрация по contract_address тут не нужна?

`next unless blockchain.contract_addresses.in?(instruction_data[:contract_address])`

2022-03-03 07:35 UTC, Nitr commented on app/models/member.rb
> +    pa.create_token_accounts
если address: nil, то токен адреса сможешь сгинерить?

2022-03-03 07:35 UTC, Nitr commented on app/models/payment_address.rb
>        create_token_account(blockchain_currency)
а тут кст есть проверка что уже токен такой есть и его не надо создавать снова?

2022-03-03 07:37 UTC, unloved commented on app/models/payment_address.rb
>        create_token_account(blockchain_currency)
есть внутри  create_token_account

2022-03-09 07:04 UTC, Nitr commented
льем? @unloved @dapi @radanisk

2022-03-09 07:32 UTC, merged