Feature #37 add create_order amqp worker
bitzlato/peatio pull request #39
Opened 2021-08-10 11:42 UTC by temacxz

[Приём заявки через websocket](https://github.com/bitzlato/peatio/issues/37)

2021-08-10 14:09 UTC, dapi requested changes

2021-08-10 14:09 UTC, dapi commented on app/services/order_services/create_order.rb
> +module OrderServices
Артем отлично начал! Круто!

Пишу общие корректировки.

1. Давай будем от params. Не люблю я эти неопознанные структуры. lДавай конкретно опишем атрибуты которые мы ждем.
2. Передаем эти атрибуты прямо в perform
3. Передаем уже готовые модели, потому что иначе. нас сервис завязан на структуру которая гоняется из API, а он не об этом.
4. В initialize передавай member, остальное в perform.

То есть получается

```
def initialize(member)
  @member = member || raise 'wtf?'
end

def perform(side:, market:, order_type:, ...)
end
```

5. Раз такая пляска переноси submit_ordeer из модели в этот сервис.

2021-08-10 14:09 UTC, dapi commented on app/services/order_services/create_order.rb
> +module OrderServices
так и тестировать проще

2021-08-10 14:09 UTC, dapi commented on app/workers/amqp/create_order.rb
> +        raise e if is_db_connection_error?(e)
Тут я так понимаю надо отправлять событие в amp. нужной форме

2021-08-10 14:10 UTC, dapi commented
👍 👍 👍

2021-08-10 14:19 UTC, dapi requested changes

2021-08-10 14:19 UTC, dapi commented on app/workers/amqp/create_order.rb
> +        report_exception(e)
исключение связанные с валидацией заказа смысла отправлять в sentry и писать в лог нет

2021-08-11 11:36 UTC, dapi commented on app/services/order_services/create_order.rb
> +      return unless order.new_record?
а че такое может быть?

2021-08-11 11:37 UTC, dapi commented on app/services/order_services/create_order.rb
> +      @market = ::Market.active.find_spot_by_symbol(market)
market сюда уже должен приходить моделью, писал выше

2021-08-11 11:37 UTC, dapi commented on app/services/order_services/create_order.rb
> +        ask:           @market&.base_unit,
@market&.base_unit -> @market.base_unit

2021-08-11 11:38 UTC, dapi commented on app/services/order_services/create_order.rb
> +      order.reload
зачем?

2021-08-11 11:38 UTC, dapi commented on app/services/order_services/create_order.rb
> +      return order.trigger_third_party_creation unless order.market.engine.peatio_engine?
че за триггер? trigger_third_party_creation нам как раз надо знать на фронте что заявка создалась, может как раз он отправляет это уведомление?

2021-08-11 11:39 UTC, dapi commented on app/workers/amqp/create_order.rb
> +      rescue StandardError => e
Account::AccountError обрабатывать отдельно, чтобы оправлять вменяемое сообщение

2021-08-11 12:06 UTC, temacxz commented on app/services/order_services/create_order.rb
> +      return order.trigger_third_party_creation unless order.market.engine.peatio_engine?
```
AMQP::Queue.publish(market.engine.driver, data: as_json_for_third_party, type: THIRD_PARTY_ORDER_ACTION_TYPE['submit_single'])
```

ну это я так понял какое-то публичное сообщение, ну раз оно тут есть, то нужно зачем-то

2021-08-11 12:07 UTC, temacxz commented on app/services/order_services/create_order.rb
> +      return order.trigger_third_party_creation unless order.market.engine.peatio_engine?
для каких-то сторонник клиентов, не для peatio (раз `unless order.market.engine.peatio_engine?`)

2021-08-11 12:24 UTC, dapi commented on app/services/order_services/create_order.rb
> +                          { persistent: false })
Кстати почему тут false?

2021-08-11 12:24 UTC, temacxz commented on app/services/order_services/create_order.rb
> +                          { persistent: false })
тоже хотел спросить

2021-08-11 12:25 UTC, temacxz commented on app/services/order_services/create_order.rb
> +                          { persistent: false })
durable: true стоит у очереди order_processor
так что поставлю true

2021-08-16 19:05 UTC, dapi requested changes

2021-08-16 19:05 UTC, dapi commented on app/services/order_services/create_order.rb
> +      order = build_order(
давай уже create_order )

2021-08-18 18:19 UTC, dapi commented on app/api/v2/order_helpers.rb
> +
шикарно )

2021-08-18 18:20 UTC, dapi commented on app/models/order.rb
>    }.freeze
👍 это все меняет, другое дело )

2021-08-18 18:20 UTC, dapi commented on app/models/order.rb
> -  after_commit :trigger_event
Почему? Может он рассчитывается не только на создание но и вообще на любое изменение?

2021-08-18 18:20 UTC, dapi commented on app/models/order.rb
>    end
👍

2021-08-18 18:21 UTC, dapi commented on app/models/order.rb
> +                          type: THIRD_PARTY_ORDER_ACTION_TYPE[:cancel_bulk])
я тут в последнее время пользую fetch вместо [] в таких случаях, так как он генерирует исключение если ключа нет. Это помогает избежать описок с названием ключа

2021-08-18 18:21 UTC, dapi commented on app/models/order.rb
> +  def trigger_private_event
А почему он private? Что в нем приватного?

2021-08-18 18:22 UTC, dapi commented on app/services/order_services/create_order.rb
> +    def perform(market:, side:, ord_type:, price: nil, volume:)
напиши плиз сверху докой какие order_type бывают

2021-08-18 18:22 UTC, dapi commented on app/services/order_services/create_order.rb
> +    end
👍

2021-08-18 18:23 UTC, dapi commented on app/services/order_services/create_order.rb
> +        'market.order.insufficient_market_liquidity',
Фронт уже умеет такое обрабатывать или надо Саше сообщить?

2021-08-18 18:25 UTC, dapi commented on app/services/order_services/create_order.rb
> +      uuid = UUID.generate
Я так понимаю в будущем можно будет:
1) Передавать uuid ордера из фронта, чтобы таким образом отслеживать его состояние. Потому что вот ошибку пришлешь и не понятно на какой именно это ордер. А фронт (точнее бот) их может генерировать сотнями;
2) Генерировать uuid на стороне постреcа, если не передан насильно. Хотя зачем..

2021-08-18 18:26 UTC, dapi commented on app/services/order_services/create_order.rb
> +      currency_unit = side == 'sell' ? market.base_unit : market.quote_unit
я бы н входе side передавал символом.
сделай плиз case с raise если ни sell ни buy

2021-08-18 18:26 UTC, dapi commented on app/services/order_services/create_order.rb
> +    end
Я ниче не понял, но верю )

2021-08-18 18:26 UTC, dapi commented on app/services/order_services/create_order.rb
> +      ) if order.is_limit_order?
А это событие куда?

2021-08-18 18:27 UTC, dapi approved these changes
💯

2021-08-19 03:16 UTC, temacxz commented on app/services/order_services/create_order.rb
> +        'market.order.insufficient_market_liquidity',
должен обратывать, ключ этот уже был до этого. НО я на всякий случай уточню у Саши

2021-08-19 08:46 UTC, temacxz commented on app/models/order.rb
> +  def trigger_private_event
приватный канал, не публичный

2021-08-19 08:47 UTC, temacxz commented on app/models/order.rb
> -  after_commit :trigger_event
логично, верну

2021-08-19 08:48 UTC, temacxz commented on app/models/order.rb
> -  after_commit :trigger_event
но это, конечно, плохо пахнущий код. Сайд эффект прописан не явно, может срабатывать когда угодно
Но пока оставлю (а то нужно будет искать все места где он тригерится и менять их)

2021-08-19 09:04 UTC, temacxz commented on app/services/order_services/create_order.rb
> +    def perform(market:, side:, ord_type:, price: nil, volume:)
+

2021-08-19 09:04 UTC, temacxz commented on app/services/order_services/create_order.rb
> +      uuid = UUID.generate
done

2021-08-19 10:57 UTC, temacxz commented on app/services/order_services/create_order.rb
> +    end
проверка стакана на наличии ликвидности чтобы выставить locked, помнишь обсуждали

2021-08-19 13:53 UTC, radanisk commented on app/services/order_services/create_order.rb
> +      ) unless POSSIBLE_SIDE_VALUES.include?(side)
Возможно, эту проверку лучше делать за пределами этого класса? Нашёл в коде ошибку с сообщением `market.order.invalid_side`. Для случая создания ордера по REST API эта проверка похоже будет осуществляться два раза.

2021-08-19 13:53 UTC, radanisk commented on app/services/order_services/create_order.rb
> +    def estimate_required_funds(price_levels:, volume:)
Подобный метод есть ещё в Order. Похоже он там больше не нужен?

2021-08-19 13:53 UTC, radanisk commented on app/services/order_services/create_order.rb
> +      market:,
Для REST API тут market тож объектом будет, не строкой? Не смог найти преобразования...

2021-08-19 13:53 UTC, radanisk commented on app/workers/amqp/create_order.rb
> +        service = ::OrderServices::CreateOrder.new(member_id, payload[:data])
::OrderServices::CreateOrder.new уже в другом формате данные принимает.

2021-08-19 13:53 UTC, radanisk commented on app/services/order_services/create_order.rb
> +    rescue StandardError => e
Может ещё обработку ::Account::AccountError сюда докинем по аналогии с REST API?

2021-08-19 14:11 UTC, temacxz commented on app/models/order_ask.rb
> -  def compute_locked
да, я до этого еще не дошел, дописываю спек на сервис. Потом буду фиксить уже остальные

2021-08-19 14:12 UTC, temacxz commented on app/services/order_services/create_order.rb
> +    # @param ord_type [String]        possible values: "limit", "market"
нет, тут только дока на поля где она нужна

2021-08-19 14:12 UTC, temacxz commented on app/services/order_services/create_order.rb
> +      ) unless POSSIBLE_SIDE_VALUES.include?(side)
гуд, спасибо

2021-08-19 14:13 UTC, temacxz commented on app/services/order_services/create_order.rb
> +    def estimate_required_funds(price_levels:, volume:)
ага, почищу

2021-08-19 14:15 UTC, temacxz commented on app/services/order_services/create_order.rb
> +      market:,
все будет объектом

2021-08-19 14:15 UTC, temacxz commented on app/workers/amqp/create_order.rb
> +        service = ::OrderServices::CreateOrder.new(member_id, payload[:data])
wip же)

2021-08-19 14:16 UTC, temacxz commented on app/services/order_services/create_order.rb
> +    rescue StandardError => e
хорошая идея, гляну

2021-08-20 17:06 UTC, dapi commented
Можно вливать или ещё VIP?

2021-08-20 17:07 UTC, temacxz commented
не, надо шлифануть еще. Я пингану тебя тут как доделаю

2021-08-24 07:19 UTC, temacxz commented on app/services/order_services/create_order.rb
> +    rescue StandardError => e
добавил, и еще сверху `ActiveRecord::RecordInvalid`

2021-08-24 07:20 UTC, temacxz commented on app/services/order_services/create_order.rb
> +      ) unless POSSIBLE_SIDE_VALUES.include?(side)
все  таки проверки контроллеров API и сервиса - разные слои. Один другой не заменяет. Этот сервис может (и уже используется) использоваться там, где нет проверок как в API

2021-08-25 11:42 UTC, radanisk commented on app/models/order.rb
> +  before_create unless: -> { Rails.env.test? } do
`unless: -> { Rails.env.test? }` выглядит как некоторый хак для тестов? :) не пропустим ли потом в тестах странных багов из-за него?

2021-08-25 11:42 UTC, radanisk commented on spec/factories/orders.rb
> +    member { create(:member) }
```suggestion
    member
```
и просто такой вариант вроде как должен подойти

2021-08-25 11:42 UTC, radanisk commented on spec/factories/orders.rb
> +    member { create(:member) }
```suggestion
    member
```
и просто такой вариант вроде как должен подойти

2021-08-25 11:42 UTC, radanisk commented on spec/lib/tasks/job_spec.rb
> -end
Тест выглядит рабочим. Зачем его удаляем?

2021-08-25 11:42 UTC, radanisk commented on spec/models/trade_spec.rb
> -  end
может лучше починить тесты, или на край в pending их закинуть?

2021-08-25 11:42 UTC, radanisk commented on spec/trading/accounting_spec.rb
> -end
А этот тест лишний?

2021-08-25 12:43 UTC, temacxz commented on app/models/order.rb
> +  before_create unless: -> { Rails.env.test? } do
это раньше было в другом месте (в submit_order), так что нет, не пропустим.
Плюс на этот кейс уже есть спек где я просто рейзю эту ошибку вручную
Этот момент мы долго обсуждали с @dapi

2021-08-25 12:44 UTC, temacxz commented on spec/factories/orders.rb
> +    member { create(:member) }
точно 👍

2021-08-25 12:56 UTC, temacxz commented on spec/lib/tasks/job_spec.rb
> -end
все удаленные тесты в этом ПРе из-за таймингов. Фиксить их всех под новые изменения слишком долго

2021-08-25 13:47 UTC, radanisk commented on spec/lib/tasks/job_spec.rb
> -end
Новые изменения именно этот тест не должны были затронуть, насколько понимаю.

2021-09-02 09:26 UTC, dapi commented on app/models/order.rb
> -  after_commit :trigger_event
Куда явнее after_commit? И ты вроде его так и не вернул

2021-09-02 09:26 UTC, dapi commented on app/models/order.rb
> -  after_commit :trigger_event
А вижу, вернул )

2021-09-03 07:58 UTC, merged