feat: add field expires_at in deposit entity
bitzlato/peatio pull request #89
Opened 2021-08-30 06:07 UTC by Alexwerber

feat: set expires_at value for invoiced deposit in migration

feat: add job that removes expired deposits

2021-08-30 13:15 UTC, radanisk requested changes

2021-08-30 13:15 UTC, radanisk commented on app/models/deposit.rb
> +      update(expires_at: nil)
@dapi может здесь сделаем более явное название для поля, вида `invoice_expired_at`. И не будем его вовсе занулять?

2021-08-30 13:15 UTC, radanisk commented on app/jobs/cron/remove_invoiced_deposits.rb
> +            deposit.cancel
Тут похоже больше bang вариант подойдёт `cancel!`?

2021-08-30 13:18 UTC, radanisk commented
@Alexwerber добавь, пожалуйста, в ревью ссылку на issue.

2021-08-31 06:10 UTC, dapi commented on app/jobs/cron/remove_invoiced_deposits.rb
> +          if deposit.expires_at < Time.now
Да, для этого поле и добавляется.

2021-08-31 06:10 UTC, dapi commented on app/jobs/cron/remove_invoiced_deposits.rb
> +            deposit.cancel
Да, если он такой есть )

2021-08-31 06:11 UTC, dapi commented on db/migrate/20210827090805_add_expires_at_field_to_deposit.rb
> +    end
да там большинство из них протухло. Но вычислять expires_at надо от даты и создания

2021-08-31 06:12 UTC, dapi requested changes
Откаментил

2021-08-31 06:13 UTC, dapi commented on app/models/deposit.rb
> +      update(expires_at: nil)
Я не против

2021-09-01 12:55 UTC, dapi commented on app/jobs/cron/remove_invoiced_deposits.rb
> +            deposit.cancel!
Тут хорошо бы еще в лог писать, что мы отменяем такой-это депозит.
`logger.info("бла-бла-бла")`

2021-09-01 12:55 UTC, dapi commented on app/jobs/cron/remove_invoiced_deposits.rb
> +      sleep(10.minutes)
10.minutes лучше вынести константой в начало касса

2021-09-03 07:57 UTC, dapi commented
👍

2021-09-03 07:57 UTC, merged